<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            1 =>
            array (
                'id' => 2,
                'surname' => 'Abdallah',
                'first_name' => 'Najoua',
                'email' => 'najoua.abdallah@student.kdg.be',
                'student_id' => '0113578-88',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'surname' => 'Amelin',
                'first_name' => 'Tatyana',
                'email' => 'tatyana.amelin@student.kdg.be',
                'student_id' => '0121114-58',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'surname' => 'Beeckmans',
                'first_name' => 'Sander',
                'email' => 'sander.beeckmans@student.kdg.be',
                'student_id' => '0123351-64',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'surname' => 'Bodson',
                'first_name' => 'Julie',
                'email' => 'julie.bodson@student.kdg.be',
                'student_id' => '0122290-70',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'surname' => 'Bogaerts',
                'first_name' => 'Jana',
                'email' => 'jana.bogaerts.1@student.kdg.be',
                'student_id' => '0122525-14',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'surname' => 'Braina',
                'first_name' => 'Delphina',
                'email' => 'delphina.braina@student.kdg.be',
                'student_id' => '0120359-79',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'surname' => 'Bruyninckx',
                'first_name' => 'Sanne',
                'email' => 'sanne.bruyninckx@student.kdg.be',
                'student_id' => '0109707-00',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'surname' => 'Burg',
                'first_name' => 'Eva',
                'email' => 'eva.burg@student.kdg.be',
                'student_id' => '0119785-87',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'surname' => 'Burleson',
                'first_name' => 'Siroe',
                'email' => 'siroe.burleson@student.kdg.be',
                'student_id' => '0118832-07',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'surname' => 'Buschop',
                'first_name' => 'Matthias',
                'email' => 'matthias.buschop@student.kdg.be',
                'student_id' => '0104103-22',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'surname' => 'Byloos',
                'first_name' => 'Juline',
                'email' => 'juline.byloos@student.kdg.be',
                'student_id' => '0118682-51',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'surname' => 'Cachimuel Iza',
                'first_name' => 'Nisa',
                'email' => 'nisa.cachimueliza@student.kdg.be',
                'student_id' => '0121649-11',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'surname' => 'Cappaert',
                'first_name' => 'Isma?l',
                'email' => 'ismael.cappaert@student.kdg.be',
                'student_id' => '0120333-53',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'surname' => 'Celis',
                'first_name' => 'Alain',
                'email' => 'alain.celis@student.kdg.be',
                'student_id' => '0120957-95',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'surname' => 'Ceulemans',
                'first_name' => 'Leni',
                'email' => 'leni.ceulemans@student.kdg.be',
                'student_id' => '0121979-50',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'surname' => 'Ciss?',
                'first_name' => 'Fatima',
                'email' => 'fatima.cisse@student.kdg.be',
                'student_id' => '0119031-12',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'surname' => 'Claus',
                'first_name' => 'Joyce',
                'email' => 'joyce.claus@student.kdg.be',
                'student_id' => '0120342-62',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'surname' => 'Cool',
                'first_name' => 'Luna',
                'email' => 'luna.cool@student.kdg.be',
                'student_id' => '0118881-56',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'surname' => 'Cornand',
                'first_name' => 'Sam',
                'email' => 'sam.cornand@student.kdg.be',
                'student_id' => '0120723-55',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'surname' => 'Dadayan',
                'first_name' => 'Tamara',
                'email' => 'tamara.dadayan@student.kdg.be',
                'student_id' => '0123154-61',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'surname' => 'Daems',
                'first_name' => 'Dennis',
                'email' => 'dennis.daems@student.kdg.be',
                'student_id' => '0122198-75',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'surname' => 'Dahman',
                'first_name' => 'Sanae',
                'email' => 'sanae.dahman@student.kdg.be',
                'student_id' => '0122970-71',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'surname' => 'De Cort',
                'first_name' => 'Christophe',
                'email' => 'christophe.decort@student.kdg.be',
                'student_id' => '0120722-54',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'surname' => 'De Jongh',
                'first_name' => 'Xsara',
                'email' => 'xsara.dejongh@student.kdg.be',
                'student_id' => '0120885-23',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'surname' => 'De Keyser',
                'first_name' => 'Viktor',
                'email' => 'viktor.dekeyser@student.kdg.be',
                'student_id' => '0121497-53',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'surname' => 'De Mulder',
                'first_name' => 'Ma?te',
                'email' => 'maite.demulder@student.kdg.be',
                'student_id' => '0121946-17',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'surname' => 'De Waal',
                'first_name' => 'Wouter',
                'email' => 'wouter.dewaal@student.kdg.be',
                'student_id' => '0122948-49',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'surname' => 'De Wachter Ottelohe',
                'first_name' => 'Amber',
                'email' => 'amber.dewachterottelohe@student.kdg.be',
                'student_id' => '0119876-81',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'surname' => 'De Wever',
                'first_name' => 'Louise',
                'email' => 'louise.dewever@student.kdg.be',
                'student_id' => '0119310-00',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'surname' => 'De Wynter',
                'first_name' => 'Dylan',
                'email' => 'dylan.dewynter@student.kdg.be',
                'student_id' => '0119189-73',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'surname' => 'Den Hartog',
                'first_name' => 'Quintina',
                'email' => 'quintina.denhartog@student.kdg.be',
                'student_id' => '0121014-55',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'surname' => 'Denissen',
                'first_name' => 'Jana',
                'email' => 'jana.denissen@student.kdg.be',
                'student_id' => '0123124-31',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'surname' => 'Dillen',
                'first_name' => 'Margo',
                'email' => 'margo.dillen@student.kdg.be',
                'student_id' => '0120675-07',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'surname' => 'D\'Joos',
                'first_name' => 'Thomas',
                'email' => 'thomas.djoos@student.kdg.be',
                'student_id' => '0116087-75',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'surname' => 'Dujardin',
                'first_name' => 'Kyara',
                'email' => 'kyara.dujardin@student.kdg.be',
                'student_id' => '0121182-29',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'surname' => 'Egghe',
                'first_name' => 'Kayley',
                'email' => 'kayley.egghe@student.kdg.be',
                'student_id' => '0120922-60',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'surname' => 'El Kadouri',
                'first_name' => 'Smail',
                'email' => 'smail.elkadouri@student.kdg.be',
                'student_id' => '0121048-89',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'surname' => 'El-Jilawi',
                'first_name' => 'Zeineb',
                'email' => 'zeineb.eljilawi@student.kdg.be',
                'student_id' => '0122953-54',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'surname' => 'Elyakim',
                'first_name' => 'Lauren',
                'email' => 'lauren.elyakim@student.kdg.be',
                'student_id' => '0107813-46',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'surname' => 'Es',
                'first_name' => 'H?ng',
                'email' => 'hong.es@student.kdg.be',
                'student_id' => '0121146-90',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'surname' => 'Esaian',
                'first_name' => 'Vivian',
                'email' => 'vivian.esaian@student.kdg.be',
                'student_id' => '0121898-66',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'surname' => 'Falzone',
                'first_name' => 'David',
                'email' => 'david.falzone@student.kdg.be',
                'student_id' => '0123478-94',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'surname' => 'Geuens',
                'first_name' => 'Adam',
                'email' => 'adam.geuens@student.kdg.be',
                'student_id' => '0122505-91',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'surname' => 'Gibbons',
                'first_name' => 'Jade',
                'email' => 'jade.gibbons@student.kdg.be',
                'student_id' => '0119793-95',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'surname' => 'Goossens',
                'first_name' => 'Mathias',
                'email' => 'mathias.goossens@student.kdg.be',
                'student_id' => '0123146-53',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'surname' => 'Goudry',
                'first_name' => 'Dorien',
                'email' => 'dorien.goudry@student.kdg.be',
                'student_id' => '0119417-10',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'surname' => 'Goyvaerts',
                'first_name' => 'Lander',
                'email' => 'lander.goyvaerts@student.kdg.be',
                'student_id' => '0119687-86',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'surname' => 'Graf Yorck Von Wartenburg',
                'first_name' => 'Albrecht',
                'email' => 'albrecht.yorck@student.kdg.be',
                'student_id' => '0120989-30',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'surname' => 'Gr?ssl',
                'first_name' => 'David',
                'email' => 'david.grossl@student.kdg.be',
                'student_id' => '0119842-47',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'surname' => 'Haeck',
                'first_name' => 'Gino',
                'email' => 'gino.haeck@student.kdg.be',
                'student_id' => '0114854-06',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'surname' => 'Handiri',
                'first_name' => 'Ghislaine',
                'email' => 'ghislaine.handiri@student.kdg.be',
                'student_id' => '0095108-48',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'surname' => 'Hardy',
                'first_name' => 'Jordan',
                'email' => 'jordan.hardy@student.kdg.be',
                'student_id' => '0118464-27',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'surname' => 'Hashim Abdulrahim',
                'first_name' => 'Uomnia',
                'email' => 'uomnia.hashimabdulrahim@student.kdg.be',
                'student_id' => '0122288-68',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'surname' => 'Heselmans',
                'first_name' => 'Vincent',
                'email' => 'vincent.heselmans@student.kdg.be',
                'student_id' => '0120102-16',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'surname' => 'Heylen',
                'first_name' => 'Maarten',
                'email' => 'maarten.heylen@student.kdg.be',
                'student_id' => '0122976-77',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'surname' => 'Hikspoors',
                'first_name' => 'Hanne',
                'email' => 'hanne.hikspoors@student.kdg.be',
                'student_id' => '0121129-73',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'surname' => 'Hofstede',
                'first_name' => 'Juliette',
                'email' => 'juliette.hofstede@student.kdg.be',
                'student_id' => '0120573-02',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'surname' => 'Houbrechts',
                'first_name' => 'Ine',
                'email' => 'ine.houbrechts@student.kdg.be',
                'student_id' => '0120904-42',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'surname' => 'Houtman',
                'first_name' => 'Wouter',
                'email' => 'wouter.houtman@student.kdg.be',
                'student_id' => '0120928-66',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'surname' => 'Jacobs',
                'first_name' => 'Joppe',
                'email' => 'joppe.jacobs@student.kdg.be',
                'student_id' => '0122964-65',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'surname' => 'Janssens',
                'first_name' => 'Lynn',
                'email' => 'lynn.janssens@student.kdg.be',
                'student_id' => '0121495-51',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'surname' => 'Janssens',
                'first_name' => 'Nolan',
                'email' => 'nolan.janssens@student.kdg.be',
                'student_id' => '0106592-86',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'surname' => 'Janssens',
                'first_name' => 'Tobias',
                'email' => 'tobias.janssens@student.kdg.be',
                'student_id' => '0115102-60',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'surname' => 'Joris',
                'first_name' => 'Janice',
                'email' => 'janice.joris@student.kdg.be',
                'student_id' => '0121053-94',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'surname' => 'Kalman',
                'first_name' => 'Klaudia',
                'email' => 'klaudia.kalman@student.kdg.be',
                'student_id' => '0120150-64',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'surname' => 'Kavalchuk',
                'first_name' => 'Yuliya',
                'email' => 'yuliya.kavalchuk@student.kdg.be',
                'student_id' => '0119307-94',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'surname' => 'Kerstens',
                'first_name' => 'Serge',
                'email' => 'serge.kerstens@student.kdg.be',
                'student_id' => '0122610-02',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'surname' => 'Kipoy Lungama',
                'first_name' => 'Jessica',
                'email' => 'jessica.kipoylungama@student.kdg.be',
                'student_id' => '0113967-89',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'surname' => 'Korsten',
                'first_name' => 'Isabelle',
                'email' => 'isabelle.korsten@student.kdg.be',
                'student_id' => '0121082-26',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'surname' => 'Leander',
                'first_name' => 'Anouk',
                'email' => 'anouk.leander@student.kdg.be',
                'student_id' => '0120731-63',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'surname' => 'Leurentop',
                'first_name' => 'Estelle',
                'email' => 'estelle.leurentop@student.kdg.be',
                'student_id' => '0121829-94',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'surname' => 'Leurentop',
                'first_name' => 'Pauline',
                'email' => 'pauline.leurentop@student.kdg.be',
                'student_id' => '0113463-70',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'surname' => 'Lodewyckx',
                'first_name' => 'Kari',
                'email' => 'kari.lodewyckx@student.kdg.be',
                'student_id' => '0116964-79',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'surname' => 'Loutfi',
                'first_name' => 'Sakina',
                'email' => 'sakina.loutfi@student.kdg.be',
                'student_id' => '0121715-77',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'surname' => 'Madrane',
                'first_name' => 'Maroua',
                'email' => 'maroua.madrane@student.kdg.be',
                'student_id' => '0116764-73',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'surname' => 'Maes',
                'first_name' => 'V?ronique',
                'email' => 'veronique.maes.2@student.kdg.be',
                'student_id' => '0111867-26',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'surname' => 'Martina',
                'first_name' => 'Lisa',
                'email' => 'lisa.martina@student.kdg.be',
                'student_id' => '0118379-39',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'surname' => 'Mechelmans',
                'first_name' => 'Elke',
                'email' => 'elke.mechelmans@student.kdg.be',
                'student_id' => '0119792-94',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'surname' => 'Michielsen',
                'first_name' => 'Evert',
                'email' => 'evert.michielsen@student.kdg.be',
                'student_id' => '0119563-59',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'surname' => 'Muyshondt',
                'first_name' => 'Zo?',
                'email' => 'zoe.muyshondt@student.kdg.be',
                'student_id' => '0119006-84',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'surname' => 'Nelissen',
                'first_name' => 'Laurika',
                'email' => 'laurika.nelissen@student.kdg.be',
                'student_id' => '0119513-09',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'surname' => 'Ngala',
                'first_name' => 'David',
                'email' => 'david.ngala@student.kdg.be',
                'student_id' => '0113836-55',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'surname' => 'Nuyts',
                'first_name' => 'Jari',
                'email' => 'jari.nuyts@student.kdg.be',
                'student_id' => '0122168-45',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'surname' => 'Omarhi-Yakala',
                'first_name' => 'Keisha',
                'email' => 'keisha.omarhiyakala@student.kdg.be',
                'student_id' => '0122593-82',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'surname' => 'Oyen',
                'first_name' => 'Wouter',
                'email' => 'wouter.oyen@student.kdg.be',
                'student_id' => '0121061-05',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'surname' => 'Paris',
                'first_name' => 'Louis',
                'email' => 'louis.paris@student.kdg.be',
                'student_id' => '0122555-44',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'surname' => 'Pauly',
                'first_name' => 'Jens',
                'email' => 'jens.pauly@student.kdg.be',
                'student_id' => '0121571-30',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'surname' => 'Pechers\'Kyy',
                'first_name' => 'Oleh',
                'email' => 'oleh.pecherskyy@student.kdg.be',
                'student_id' => '0119161-45',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'surname' => 'Peeters',
                'first_name' => 'Lisa',
                'email' => 'lisa.peeters@student.kdg.be',
                'student_id' => '0121621-80',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'surname' => 'Peeters',
                'first_name' => 'Miro',
                'email' => 'miro.peeters@student.kdg.be',
                'student_id' => '0121579-38',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'surname' => 'Peremans',
                'first_name' => 'Karen',
                'email' => 'karen.peremans@student.kdg.be',
                'student_id' => '0120959-00',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'surname' => 'Pets',
                'first_name' => 'Sam',
                'email' => 'sam.pets@student.kdg.be',
                'student_id' => '0092260-13',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'surname' => 'Pham',
                'first_name' => 'Joachim',
                'email' => 'joachim.pham@student.kdg.be',
                'student_id' => '0112366-40',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'surname' => 'Pire',
                'first_name' => 'Loriane',
                'email' => 'loriane.pire@student.kdg.be',
                'student_id' => '0120145-59',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'surname' => 'Poppe',
                'first_name' => 'Joren',
                'email' => 'joren.poppe@student.kdg.be',
                'student_id' => '0120589-18',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'surname' => 'Puggioni',
                'first_name' => 'Eros',
                'email' => 'eros.puggioni@student.kdg.be',
                'student_id' => '0120655-84',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'surname' => 'Pynaerts',
                'first_name' => 'Venuto',
                'email' => 'venuto.pynaerts@student.kdg.be',
                'student_id' => '0118907-82',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'surname' => 'Roovers',
                'first_name' => 'Rein',
                'email' => 'rein.roovers@student.kdg.be',
                'student_id' => '0123139-46',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'surname' => 'Schaub',
                'first_name' => 'Emile',
                'email' => 'emile.schaub@student.kdg.be',
                'student_id' => '0123029-33',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'surname' => 'Schro?',
                'first_name' => 'Jonas',
                'email' => 'jonas.schroe@student.kdg.be',
                'student_id' => '0120863-01',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'surname' => 'Servaes',
                'first_name' => 'Elise',
                'email' => 'elise.servaes@student.kdg.be',
                'student_id' => '0118433-93',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 9,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'surname' => 'Seynaeve',
                'first_name' => 'Romain',
                'email' => 'romain.seynaeve@student.kdg.be',
                'student_id' => '0118706-75',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'surname' => 'Sneiders',
                'first_name' => 'Merel',
                'email' => 'merel.sneiders@student.kdg.be',
                'student_id' => '0114954-09',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'surname' => 'Spinnox',
                'first_name' => 'Dewi-Maya',
                'email' => 'dewimaya.spinnox@student.kdg.be',
                'student_id' => '0121716-78',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'surname' => 'Symons',
                'first_name' => 'Lisa',
                'email' => 'lisa.symons@student.kdg.be',
                'student_id' => '0118858-33',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'surname' => 'Tarcan',
                'first_name' => 'Z?lal',
                'email' => 'zulal.tarcan@student.kdg.be',
                'student_id' => '0123529-48',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'surname' => 'Theuwissen',
                'first_name' => 'Dorien',
                'email' => 'dorien.theuwissen@student.kdg.be',
                'student_id' => '0120856-91',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'surname' => 'Thoen',
                'first_name' => 'Eva',
                'email' => 'eva.thoen@student.kdg.be',
                'student_id' => '0119180-64',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'surname' => 'Truong Van',
                'first_name' => 'Kevin',
                'email' => 'van.truong@student.kdg.be',
                'student_id' => '0122575-64',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 9,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'surname' => 'U?ar',
                'first_name' => 'Yelena',
                'email' => 'yelena.ucar@student.kdg.be',
                'student_id' => '0120934-72',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'surname' => 'Van Den Broek',
                'first_name' => 'Gwen',
                'email' => 'gwen.vandenbroek@student.kdg.be',
                'student_id' => '0107477-01',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'surname' => 'Van Den Maegdenbergh',
                'first_name' => 'Ma?t?',
                'email' => 'maite.vandenmaegdenbergh@student.kdg.be',
                'student_id' => '0108472-26',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'surname' => 'Van Der Veken',
                'first_name' => 'Tom',
            'email' => '(tom.vanderveken@student.kdg.be)',
                'student_id' => '0112333-07',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'surname' => 'Van Dessel',
                'first_name' => 'Lies',
                'email' => 'lies.vandessel@student.kdg.be',
                'student_id' => '0122507-93',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'surname' => 'Van Deun',
                'first_name' => 'Luna',
                'email' => 'luna.vandeun@student.kdg.be',
                'student_id' => '0118664-33',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'surname' => 'Van Geeteruyen',
                'first_name' => 'Christof',
                'email' => 'christof.vangeeteruyen@student.kdg.be',
                'student_id' => '0114301-35',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'surname' => 'Van Lokeren',
                'first_name' => 'Koen',
                'email' => 'koen.vanlokeren@student.kdg.be',
                'student_id' => '0114274-08',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'surname' => 'Van Opstal',
                'first_name' => 'Thomas',
                'email' => 'thomas.vanopstal@student.kdg.be',
                'student_id' => '0121713-75',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'surname' => 'Van Schil',
                'first_name' => 'Veerle',
                'email' => 'veerle.vanschil@student.kdg.be',
                'student_id' => '0119218-05',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'surname' => 'Van Thiel',
                'first_name' => 'Laurique',
                'email' => 'laurique.vanthiel@student.kdg.be',
                'student_id' => '0123002-06',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'surname' => 'Varendonck',
                'first_name' => 'Charlotte',
                'email' => 'charlotte.varendonck@student.kdg.be',
                'student_id' => '0120266-83',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'surname' => 'Vastmans',
                'first_name' => 'Julie',
                'email' => 'julie.vastmans@student.kdg.be',
                'student_id' => '0121262-12',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'surname' => 'Verbruggen',
                'first_name' => 'Natan',
                'email' => 'natan.verbruggen@student.kdg.be',
                'student_id' => '0122961-62',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'surname' => 'Vercauteren',
                'first_name' => 'Dennis',
                'email' => 'dennis.vercauteren@student.kdg.be',
                'student_id' => '0101586-27',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'surname' => 'Verellen',
                'first_name' => 'Glenn',
                'email' => 'glenn.verellen@student.kdg.be',
                'student_id' => '0118867-42',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'surname' => 'Verheyen',
                'first_name' => 'Wannes',
                'email' => 'wannes.verheyen@student.kdg.be',
                'student_id' => '0120317-37',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 9,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'surname' => 'Verhoeven',
                'first_name' => 'Tobias',
                'email' => 'tobias.verhoeven@student.kdg.be',
                'student_id' => '0123319-32',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'surname' => 'Verlinden',
                'first_name' => 'Helena',
                'email' => 'helena.verlinden@student.kdg.be',
                'student_id' => '0122043-17',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'surname' => 'Verlinden',
                'first_name' => 'Jasper',
                'email' => 'jasper.verlinden@student.kdg.be',
                'student_id' => '0121992-63',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'surname' => 'Verlouw',
                'first_name' => 'Kees',
                'email' => 'kees.verlouw@student.kdg.be',
                'student_id' => '0122083-57',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'surname' => 'Vermeir',
                'first_name' => 'Hannelore',
                'email' => 'hannelore.vermeir@student.kdg.be',
                'student_id' => '0120095-09',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'surname' => 'Vervloet',
                'first_name' => 'Laurence',
                'email' => 'laurence.vervloet@student.kdg.be',
                'student_id' => '0115629-05',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'surname' => 'Villagran Martinetty',
                'first_name' => 'Krystell',
                'email' => 'krystell.villagranmartinetty@student.kdg.be',
                'student_id' => '0112859-48',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'surname' => 'Vorsters',
                'first_name' => 'Kristien',
                'email' => 'kristien.vorsters@student.kdg.be',
                'student_id' => '0122854-52',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'surname' => 'Vranken',
                'first_name' => 'Ines',
                'email' => 'ines.vranken@student.kdg.be',
                'student_id' => '0121355-08',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 9,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'surname' => 'Weiremans',
                'first_name' => 'Lorenz',
                'email' => 'lorenz.weiremans@student.kdg.be',
                'student_id' => '0122981-82',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'surname' => 'Wellens',
                'first_name' => 'Justine',
                'email' => 'justine.wellens@student.kdg.be',
                'student_id' => '0122482-68',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'surname' => 'Willems',
                'first_name' => 'Joke',
                'email' => 'joke.willems@student.kdg.be',
                'student_id' => '0121422-75',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'surname' => 'Winterink',
                'first_name' => 'Jet',
                'email' => 'jet.winterink@student.kdg.be',
                'student_id' => '0119120-04',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'surname' => 'Zherka',
                'first_name' => 'Altin',
                'email' => 'altin.zherka@student.kdg.be',
                'student_id' => '0122860-58',
                'password' => NULL,
                'is_admin' => 0,
                'class_group_id' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}
